spring:
  application:
    name: eureka-client
server:
  port: 8761

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8090/eureka

db:
  url: jdbc:mysql://mysql:3306/user_mgm
  username: root
  password: root
  driver: com.mysql.jdbc.Driver


hibernate:
  dialect: org.hibernate.dialect.MySQL5Dialect
  show_sql: true
  hbm2ddl:
    auto: update